### ISSUE TITLE
gcode execution problem

### ISSUE THREAD

**Issue by gokulvenkat** [CCHS-Melbourne/CNC-Mini-Mill#1]
hi i am using fusion360 for gcode generation ,i use marlin firmware with arduino mega2560 and ramp1.4 .the issue i am seeing is if gcode for example
G0 X0 YO
G01 X10 Y20 F200
X20 Y30
X40 Y40
in which G01 X10 Y20 WORKS WELL AND gcode line without G01 AND G0 is not been executed
but cnc controlled by fanuc will execute it .so how to solve it please any one help me

**Comment by rdpowers** [comment]
I think this is the expected operation. G-Code command parsing & exection happens in Marlin_main.cpp and the CASE statement looks for full commands (Those starting with Gxxx or Mxxx:
https://github.com/CCHS-Melbourne/CNC-Mini-Mill/blob/master/Firmware/Marlin-Marlin_v1/Marlin/Marlin_main.cpp#L657

The fix would be to have Fusion360 generate complete lines for all commands. I'm guessing there's an option for this.

Also, I have no idea if this repo contains the firmware on the mini-mill...

**Comment by maximkon89** [comment]
how download firmware?

**Comment by gokulvenkat** [comment]
Issue solved i used a post process file to generate gcode ,i. Got it from rclifeon in YouTube with acrylic milling
